language: android

android:
  components:
    - tools                             # Tools
    - platform-tools                    # Platform tools
    - build-tools-28.0.3                # Build tools version
    - android-28                        # Target SDK version
    - extra-android-m2repository        # Support repo

jdk:
  - oraclejdk8

script:
  - ./gradlew build

after_success:
    - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "SONATYPE_NEXUS_USERNAME TODO"
    - secure: "SONATYPE_NEXUS_PASSWORD TODO"

branches:
  except:
    - gh-pages

notifications:
  email: false

cache:
  directories:
    - $HOME/.gradle
